name: CI for Astrobite Burgers

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:latest
        options: --privileged
        ports:
          - 5000:5000

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Stop any running containers on port 5000
      run: |
        docker ps -q --filter "publish=5000" | xargs -r docker stop
        docker ps -a -q --filter "publish=5000" | xargs -r docker rm

    - name: Build Docker image
      run: |
        docker build -t flask-server .

    - name: Run Docker container
      run: |
        docker run -d -p 5000:5000 --name astrobite-burguers flask-server
        # Wait for Flask to be ready
        for i in {1..30}; do
          if curl --silent --fail http://localhost:5000; then
            echo "Flask is up!"
            break
          fi
          echo "Waiting for Flask to start..."
          sleep 5
        done

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest -v tests/test_routes.py

    - name: Clean up Docker containers
      run: |
        docker stop astrobite-burguers
        docker rm astrobite-burguers

    - name: View container logs
      run: |
        docker logs astrobite-burguers
