name: CI/CD for Astrobite Burgers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest -v tests/

  deploy:
    needs: test  # Will only deploy if approved by tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Railway
        env:
            RAILWAY_API_TOKEN: ${{ secrets['RAILWAY_API_TOKEN'] }}
        run: |
          curl -fsSL https://cli.railway.app/install.sh | sh
          railway up --production
